dbt_retail:
  outputs:
    dev:
      account: xub44819.us-east-1
      database: RETAIL_DEV
      password: OneBlood123
      role: DEVELOPER
      schema: DBT_SBROWN
      threads: 1
      type: snowflake
      user: TRANSFORM_USER
      warehouse: HEALTHCARE_WH
  target: dev
