dbt_retail:
  outputs:
    dev:
      account
      database: RETAIL_DEV
      password:
      role: DEVELOPER
      schema: DBT_SBROWN
      threads: 1
      type: snowflake
      user: TRANSFORM_USER
      warehouse: HEALTHCARE_WH
  target: dev
